//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string current_paramsField;
        
        private string current_request_nameField;
        
        private string nested_exceptionField;
        
        private DataServiceFaultSource_data_service source_data_serviceField;
        
        private string ds_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string current_params {
            get {
                return this.current_paramsField;
            }
            set {
                this.current_paramsField = value;
                this.RaisePropertyChanged("current_params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string current_request_name {
            get {
                return this.current_request_nameField;
            }
            set {
                this.current_request_nameField = value;
                this.RaisePropertyChanged("current_request_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nested_exception {
            get {
                return this.nested_exceptionField;
            }
            set {
                this.nested_exceptionField = value;
                this.RaisePropertyChanged("nested_exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DataServiceFaultSource_data_service source_data_service {
            get {
                return this.source_data_serviceField;
            }
            set {
                this.source_data_serviceField = value;
                this.RaisePropertyChanged("source_data_service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ds_code {
            get {
                return this.ds_codeField;
            }
            set {
                this.ds_codeField = value;
                this.RaisePropertyChanged("ds_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFaultSource_data_service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationField;
        
        private string default_namespaceField;
        
        private string descriptionField;
        
        private string data_service_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string default_namespace {
            get {
                return this.default_namespaceField;
            }
            set {
                this.default_namespaceField = value;
                this.RaisePropertyChanged("default_namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string data_service_name {
            get {
                return this.data_service_nameField;
            }
            set {
                this.data_service_nameField = value;
                this.RaisePropertyChanged("data_service_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/login")]
    public partial class Entry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nOMBREUSUARIOField;
        
        private string cONTRASENAField;
        
        private string eSTADOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string NOMBREUSUARIO {
            get {
                return this.nOMBREUSUARIOField;
            }
            set {
                this.nOMBREUSUARIOField = value;
                this.RaisePropertyChanged("NOMBREUSUARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string CONTRASENA {
            get {
                return this.cONTRASENAField;
            }
            set {
                this.cONTRASENAField = value;
                this.RaisePropertyChanged("CONTRASENA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pica.com/dss/login", ConfigurationName="wsAutenticacionReference.wsAutenticacionPortType")]
    public interface wsAutenticacionPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (Entries) of message wsAutenticacionUsuarioResponse does not match the default value (wsAutenticacionUsuario)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsAutenticacionUsuario", ReplyAction="urn:wsAutenticacionUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.DataServiceFault), Action="urn:wsAutenticacionUsuarioDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioResponse wsAutenticacionUsuario(PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsAutenticacionUsuario", ReplyAction="urn:wsAutenticacionUsuarioResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioResponse> wsAutenticacionUsuarioAsync(PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsAutenticacionUsuario", WrapperNamespace="http://pica.com/dss/login", IsWrapped=true)]
    public partial class wsAutenticacionUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/login", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string USUARIOLOGIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/login", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PASSWORDUSUARIO;
        
        public wsAutenticacionUsuarioRequest() {
        }
        
        public wsAutenticacionUsuarioRequest(string USUARIOLOGIN, string PASSWORDUSUARIO) {
            this.USUARIOLOGIN = USUARIOLOGIN;
            this.PASSWORDUSUARIO = PASSWORDUSUARIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Entries", WrapperNamespace="http://pica.com/dss/login", IsWrapped=true)]
    public partial class wsAutenticacionUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/login", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Entry")]
        public PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.Entry[] Entry;
        
        public wsAutenticacionUsuarioResponse() {
        }
        
        public wsAutenticacionUsuarioResponse(PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.Entry[] Entry) {
            this.Entry = Entry;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAutenticacionPortTypeChannel : PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAutenticacionPortTypeClient : System.ServiceModel.ClientBase<PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionPortType>, PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionPortType {
        
        public wsAutenticacionPortTypeClient() {
        }
        
        public wsAutenticacionPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAutenticacionPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAutenticacionPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAutenticacionPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioResponse PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionPortType.wsAutenticacionUsuario(PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioRequest request) {
            return base.Channel.wsAutenticacionUsuario(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.Entry[] wsAutenticacionUsuario(string USUARIOLOGIN, string PASSWORDUSUARIO) {
            PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioRequest();
            inValue.USUARIOLOGIN = USUARIOLOGIN;
            inValue.PASSWORDUSUARIO = PASSWORDUSUARIO;
            PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionPortType)(this)).wsAutenticacionUsuario(inValue);
            return retVal.Entry;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioResponse> PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionPortType.wsAutenticacionUsuarioAsync(PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioRequest request) {
            return base.Channel.wsAutenticacionUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioResponse> wsAutenticacionUsuarioAsync(string USUARIOLOGIN, string PASSWORDUSUARIO) {
            PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionUsuarioRequest();
            inValue.USUARIOLOGIN = USUARIOLOGIN;
            inValue.PASSWORDUSUARIO = PASSWORDUSUARIO;
            return ((PICA_B2C.ServiceAgent.MainModule.wsAutenticacionReference.wsAutenticacionPortType)(this)).wsAutenticacionUsuarioAsync(inValue);
        }
    }
}
