//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string current_paramsField;
        
        private string current_request_nameField;
        
        private string nested_exceptionField;
        
        private DataServiceFaultSource_data_service source_data_serviceField;
        
        private string ds_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string current_params {
            get {
                return this.current_paramsField;
            }
            set {
                this.current_paramsField = value;
                this.RaisePropertyChanged("current_params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string current_request_name {
            get {
                return this.current_request_nameField;
            }
            set {
                this.current_request_nameField = value;
                this.RaisePropertyChanged("current_request_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nested_exception {
            get {
                return this.nested_exceptionField;
            }
            set {
                this.nested_exceptionField = value;
                this.RaisePropertyChanged("nested_exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DataServiceFaultSource_data_service source_data_service {
            get {
                return this.source_data_serviceField;
            }
            set {
                this.source_data_serviceField = value;
                this.RaisePropertyChanged("source_data_service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ds_code {
            get {
                return this.ds_codeField;
            }
            set {
                this.ds_codeField = value;
                this.RaisePropertyChanged("ds_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFaultSource_data_service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationField;
        
        private string default_namespaceField;
        
        private string descriptionField;
        
        private string data_service_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string default_namespace {
            get {
                return this.default_namespaceField;
            }
            set {
                this.default_namespaceField = value;
                this.RaisePropertyChanged("default_namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string data_service_name {
            get {
                return this.data_service_nameField;
            }
            set {
                this.data_service_nameField = value;
                this.RaisePropertyChanged("data_service_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Productos")]
    public partial class Elemento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cANTIDADField;
        
        private string pRODIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
                this.RaisePropertyChanged("CANTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string PRODID {
            get {
                return this.pRODIDField;
            }
            set {
                this.pRODIDField = value;
                this.RaisePropertyChanged("PRODID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pica.com/dss/Productos", ConfigurationName="wsTopProductsReference.topProductosPortType")]
    public interface topProductosPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (Elementos) of message wsTopCincoResponse does not match the default value (wsTopCinco)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsTopCinco", ReplyAction="urn:wsTopCincoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.DataServiceFault), Action="urn:wsTopCincoDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoResponse wsTopCinco(PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsTopCinco", ReplyAction="urn:wsTopCincoResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoResponse> wsTopCincoAsync(PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsTopCinco", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsTopCincoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PRODID_IN;
        
        public wsTopCincoRequest() {
        }
        
        public wsTopCincoRequest(System.Nullable<int> PRODID_IN) {
            this.PRODID_IN = PRODID_IN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Elementos", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsTopCincoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Elemento")]
        public PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.Elemento[] Elemento;
        
        public wsTopCincoResponse() {
        }
        
        public wsTopCincoResponse(PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.Elemento[] Elemento) {
            this.Elemento = Elemento;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface topProductosPortTypeChannel : PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.topProductosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class topProductosPortTypeClient : System.ServiceModel.ClientBase<PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.topProductosPortType>, PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.topProductosPortType {
        
        public topProductosPortTypeClient() {
        }
        
        public topProductosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public topProductosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public topProductosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public topProductosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoResponse PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.topProductosPortType.wsTopCinco(PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoRequest request) {
            return base.Channel.wsTopCinco(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.Elemento[] wsTopCinco(System.Nullable<int> PRODID_IN) {
            PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoRequest();
            inValue.PRODID_IN = PRODID_IN;
            PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.topProductosPortType)(this)).wsTopCinco(inValue);
            return retVal.Elemento;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoResponse> PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.topProductosPortType.wsTopCincoAsync(PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoRequest request) {
            return base.Channel.wsTopCincoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoResponse> wsTopCincoAsync(System.Nullable<int> PRODID_IN) {
            PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.wsTopCincoRequest();
            inValue.PRODID_IN = PRODID_IN;
            return ((PICA_B2C.ServiceAgent.MainModule.wsTopProductsReference.topProductosPortType)(this)).wsTopCincoAsync(inValue);
        }
    }
}
