//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string current_paramsField;
        
        private string current_request_nameField;
        
        private string nested_exceptionField;
        
        private DataServiceFaultSource_data_service source_data_serviceField;
        
        private string ds_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string current_params {
            get {
                return this.current_paramsField;
            }
            set {
                this.current_paramsField = value;
                this.RaisePropertyChanged("current_params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string current_request_name {
            get {
                return this.current_request_nameField;
            }
            set {
                this.current_request_nameField = value;
                this.RaisePropertyChanged("current_request_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nested_exception {
            get {
                return this.nested_exceptionField;
            }
            set {
                this.nested_exceptionField = value;
                this.RaisePropertyChanged("nested_exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DataServiceFaultSource_data_service source_data_service {
            get {
                return this.source_data_serviceField;
            }
            set {
                this.source_data_serviceField = value;
                this.RaisePropertyChanged("source_data_service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ds_code {
            get {
                return this.ds_codeField;
            }
            set {
                this.ds_codeField = value;
                this.RaisePropertyChanged("ds_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFaultSource_data_service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationField;
        
        private string default_namespaceField;
        
        private string descriptionField;
        
        private string data_service_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string default_namespace {
            get {
                return this.default_namespaceField;
            }
            set {
                this.default_namespaceField = value;
                this.RaisePropertyChanged("default_namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string data_service_name {
            get {
                return this.data_service_nameField;
            }
            set {
                this.data_service_nameField = value;
                this.RaisePropertyChanged("data_service_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Productos")]
    public partial class RankingProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cANTIDADORDENESField;
        
        private string pRODIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string CANTIDADORDENES {
            get {
                return this.cANTIDADORDENESField;
            }
            set {
                this.cANTIDADORDENESField = value;
                this.RaisePropertyChanged("CANTIDADORDENES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string PRODID {
            get {
                return this.pRODIDField;
            }
            set {
                this.pRODIDField = value;
                this.RaisePropertyChanged("PRODID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pica.com/dss/Productos", ConfigurationName="wsConsultasProductosReference.consultasEspecialesProductosPortType")]
    public interface consultasEspecialesProductosPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (RankingProductos) of message wsRankingProductosResponse does not match the default value (wsRankingProductos)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsRankingProductos", ReplyAction="urn:wsRankingProductosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.DataServiceFault), Action="urn:wsRankingProductosDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosResponse wsRankingProductos(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsRankingProductos", ReplyAction="urn:wsRankingProductosResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosResponse> wsRankingProductosAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaProsXNombre) of message wsBuscarproductosXNombreResponse does not match the default value (wsBuscarproductosXNombre)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsBuscarproductosXNombre", ReplyAction="urn:wsBuscarproductosXNombreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.DataServiceFault), Action="urn:wsBuscarproductosXNombreDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreResponse wsBuscarproductosXNombre(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsBuscarproductosXNombre", ReplyAction="urn:wsBuscarproductosXNombreResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreResponse> wsBuscarproductosXNombreAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (RankingCategorias) of message wsRankingCategoriasResponse does not match the default value (wsRankingCategorias)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsRankingCategorias", ReplyAction="urn:wsRankingCategoriasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.DataServiceFault), Action="urn:wsRankingCategoriasDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasResponse wsRankingCategorias(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsRankingCategorias", ReplyAction="urn:wsRankingCategoriasResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasResponse> wsRankingCategoriasAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaProductosXID) of message wsBuscarproductoXIDResponse does not match the default value (wsBuscarproductoXID)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsBuscarproductoXID", ReplyAction="urn:wsBuscarproductoXIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.DataServiceFault), Action="urn:wsBuscarproductoXIDDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDResponse wsBuscarproductoXID(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsBuscarproductoXID", ReplyAction="urn:wsBuscarproductoXIDResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDResponse> wsBuscarproductoXIDAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConsultaProtosXDes) of message wsBuscarProductosXDescripcionResponse does not match the default value (wsBuscarProductosXDescripcion)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsBuscarProductosXDescripcion", ReplyAction="urn:wsBuscarProductosXDescripcionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.DataServiceFault), Action="urn:wsBuscarProductosXDescripcionDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionResponse wsBuscarProductosXDescripcion(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsBuscarProductosXDescripcion", ReplyAction="urn:wsBuscarProductosXDescripcionResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionResponse> wsBuscarProductosXDescripcionAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsRankingProductos", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsRankingProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHAINI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHAFIN;
        
        public wsRankingProductosRequest() {
        }
        
        public wsRankingProductosRequest(string FECHAINI, string FECHAFIN) {
            this.FECHAINI = FECHAINI;
            this.FECHAFIN = FECHAFIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RankingProductos", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsRankingProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RankingProducto")]
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.RankingProducto[] RankingProducto;
        
        public wsRankingProductosResponse() {
        }
        
        public wsRankingProductosResponse(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.RankingProducto[] RankingProducto) {
            this.RankingProducto = RankingProducto;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Productos")]
    public partial class ConsultaProXNombre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cANTIDAD_REGISTROSField;
        
        private string idField;
        
        private string pRODUCTO_IDField;
        
        private string nOMBREField;
        
        private string dESCRIPCIONField;
        
        private string cATEGORIAField;
        
        private string pRECIO_LISTAField;
        
        private string fABRICANTEField;
        
        private string iMAGENField;
        
        private string iMAGEN_URLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string CANTIDAD_REGISTROS {
            get {
                return this.cANTIDAD_REGISTROSField;
            }
            set {
                this.cANTIDAD_REGISTROSField = value;
                this.RaisePropertyChanged("CANTIDAD_REGISTROS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string PRODUCTO_ID {
            get {
                return this.pRODUCTO_IDField;
            }
            set {
                this.pRODUCTO_IDField = value;
                this.RaisePropertyChanged("PRODUCTO_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
                this.RaisePropertyChanged("CATEGORIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=6)]
        public string PRECIO_LISTA {
            get {
                return this.pRECIO_LISTAField;
            }
            set {
                this.pRECIO_LISTAField = value;
                this.RaisePropertyChanged("PRECIO_LISTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string FABRICANTE {
            get {
                return this.fABRICANTEField;
            }
            set {
                this.fABRICANTEField = value;
                this.RaisePropertyChanged("FABRICANTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string IMAGEN {
            get {
                return this.iMAGENField;
            }
            set {
                this.iMAGENField = value;
                this.RaisePropertyChanged("IMAGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string IMAGEN_URL {
            get {
                return this.iMAGEN_URLField;
            }
            set {
                this.iMAGEN_URLField = value;
                this.RaisePropertyChanged("IMAGEN_URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsBuscarproductosXNombre", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsBuscarproductosXNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NOMBRE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NUMERO_PAGINA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TAMANO_PAGINA;
        
        public wsBuscarproductosXNombreRequest() {
        }
        
        public wsBuscarproductosXNombreRequest(string NOMBRE, System.Nullable<int> NUMERO_PAGINA, System.Nullable<int> TAMANO_PAGINA) {
            this.NOMBRE = NOMBRE;
            this.NUMERO_PAGINA = NUMERO_PAGINA;
            this.TAMANO_PAGINA = TAMANO_PAGINA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaProsXNombre", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsBuscarproductosXNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ConsultaProXNombre")]
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProXNombre[] ConsultaProXNombre;
        
        public wsBuscarproductosXNombreResponse() {
        }
        
        public wsBuscarproductosXNombreResponse(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProXNombre[] ConsultaProXNombre) {
            this.ConsultaProXNombre = ConsultaProXNombre;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Productos")]
    public partial class RankingCategoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cANTIDADORDENESField;
        
        private string pRODUCTCATEGORIAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string CANTIDADORDENES {
            get {
                return this.cANTIDADORDENESField;
            }
            set {
                this.cANTIDADORDENESField = value;
                this.RaisePropertyChanged("CANTIDADORDENES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string PRODUCTCATEGORIA {
            get {
                return this.pRODUCTCATEGORIAField;
            }
            set {
                this.pRODUCTCATEGORIAField = value;
                this.RaisePropertyChanged("PRODUCTCATEGORIA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsRankingCategorias", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsRankingCategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHAINI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHAFIN;
        
        public wsRankingCategoriasRequest() {
        }
        
        public wsRankingCategoriasRequest(string FECHAINI, string FECHAFIN) {
            this.FECHAINI = FECHAINI;
            this.FECHAFIN = FECHAFIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RankingCategorias", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsRankingCategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RankingCategoria")]
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.RankingCategoria[] RankingCategoria;
        
        public wsRankingCategoriasResponse() {
        }
        
        public wsRankingCategoriasResponse(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.RankingCategoria[] RankingCategoria) {
            this.RankingCategoria = RankingCategoria;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Productos")]
    public partial class ConsultaProductoXID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string pRODUCTO_IDField;
        
        private string nOMBREField;
        
        private string dESCRIPCIONField;
        
        private string cATEGORIAField;
        
        private string pRECIO_LISTAField;
        
        private string fABRICANTEField;
        
        private string iMAGENField;
        
        private string iMAGEN_URLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string PRODUCTO_ID {
            get {
                return this.pRODUCTO_IDField;
            }
            set {
                this.pRODUCTO_IDField = value;
                this.RaisePropertyChanged("PRODUCTO_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
                this.RaisePropertyChanged("CATEGORIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string PRECIO_LISTA {
            get {
                return this.pRECIO_LISTAField;
            }
            set {
                this.pRECIO_LISTAField = value;
                this.RaisePropertyChanged("PRECIO_LISTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string FABRICANTE {
            get {
                return this.fABRICANTEField;
            }
            set {
                this.fABRICANTEField = value;
                this.RaisePropertyChanged("FABRICANTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string IMAGEN {
            get {
                return this.iMAGENField;
            }
            set {
                this.iMAGENField = value;
                this.RaisePropertyChanged("IMAGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string IMAGEN_URL {
            get {
                return this.iMAGEN_URLField;
            }
            set {
                this.iMAGEN_URLField = value;
                this.RaisePropertyChanged("IMAGEN_URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsBuscarproductoXID", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsBuscarproductoXIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PRODUCTO_ID;
        
        public wsBuscarproductoXIDRequest() {
        }
        
        public wsBuscarproductoXIDRequest(System.Nullable<int> PRODUCTO_ID) {
            this.PRODUCTO_ID = PRODUCTO_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaProductosXID", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsBuscarproductoXIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ConsultaProductoXID")]
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProductoXID[] ConsultaProductoXID;
        
        public wsBuscarproductoXIDResponse() {
        }
        
        public wsBuscarproductoXIDResponse(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProductoXID[] ConsultaProductoXID) {
            this.ConsultaProductoXID = ConsultaProductoXID;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Productos")]
    public partial class ConsultaProXDes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cANTIDAD_REGISTROSField;
        
        private string idField;
        
        private string pRODUCTO_IDField;
        
        private string nOMBREField;
        
        private string dESCRIPCIONField;
        
        private string cATEGORIAField;
        
        private string pRECIO_LISTAField;
        
        private string fABRICANTEField;
        
        private string iMAGENField;
        
        private string iMAGEN_URLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string CANTIDAD_REGISTROS {
            get {
                return this.cANTIDAD_REGISTROSField;
            }
            set {
                this.cANTIDAD_REGISTROSField = value;
                this.RaisePropertyChanged("CANTIDAD_REGISTROS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string PRODUCTO_ID {
            get {
                return this.pRODUCTO_IDField;
            }
            set {
                this.pRODUCTO_IDField = value;
                this.RaisePropertyChanged("PRODUCTO_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
                this.RaisePropertyChanged("CATEGORIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=6)]
        public string PRECIO_LISTA {
            get {
                return this.pRECIO_LISTAField;
            }
            set {
                this.pRECIO_LISTAField = value;
                this.RaisePropertyChanged("PRECIO_LISTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string FABRICANTE {
            get {
                return this.fABRICANTEField;
            }
            set {
                this.fABRICANTEField = value;
                this.RaisePropertyChanged("FABRICANTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string IMAGEN {
            get {
                return this.iMAGENField;
            }
            set {
                this.iMAGENField = value;
                this.RaisePropertyChanged("IMAGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string IMAGEN_URL {
            get {
                return this.iMAGEN_URLField;
            }
            set {
                this.iMAGEN_URLField = value;
                this.RaisePropertyChanged("IMAGEN_URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsBuscarProductosXDescripcion", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsBuscarProductosXDescripcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DESCRIPCION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NUMERO_PAGINA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TAMANO_PAGINA;
        
        public wsBuscarProductosXDescripcionRequest() {
        }
        
        public wsBuscarProductosXDescripcionRequest(string DESCRIPCION, System.Nullable<int> NUMERO_PAGINA, System.Nullable<int> TAMANO_PAGINA) {
            this.DESCRIPCION = DESCRIPCION;
            this.NUMERO_PAGINA = NUMERO_PAGINA;
            this.TAMANO_PAGINA = TAMANO_PAGINA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaProtosXDes", WrapperNamespace="http://pica.com/dss/Productos", IsWrapped=true)]
    public partial class wsBuscarProductosXDescripcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Productos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ConsultaProXDes")]
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProXDes[] ConsultaProXDes;
        
        public wsBuscarProductosXDescripcionResponse() {
        }
        
        public wsBuscarProductosXDescripcionResponse(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProXDes[] ConsultaProXDes) {
            this.ConsultaProXDes = ConsultaProXDes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface consultasEspecialesProductosPortTypeChannel : PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class consultasEspecialesProductosPortTypeClient : System.ServiceModel.ClientBase<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType>, PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType {
        
        public consultasEspecialesProductosPortTypeClient() {
        }
        
        public consultasEspecialesProductosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public consultasEspecialesProductosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public consultasEspecialesProductosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public consultasEspecialesProductosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosResponse PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsRankingProductos(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosRequest request) {
            return base.Channel.wsRankingProductos(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.RankingProducto[] wsRankingProductos(string FECHAINI, string FECHAFIN) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosRequest();
            inValue.FECHAINI = FECHAINI;
            inValue.FECHAFIN = FECHAFIN;
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsRankingProductos(inValue);
            return retVal.RankingProducto;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosResponse> PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsRankingProductosAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosRequest request) {
            return base.Channel.wsRankingProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosResponse> wsRankingProductosAsync(string FECHAINI, string FECHAFIN) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingProductosRequest();
            inValue.FECHAINI = FECHAINI;
            inValue.FECHAFIN = FECHAFIN;
            return ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsRankingProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreResponse PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsBuscarproductosXNombre(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreRequest request) {
            return base.Channel.wsBuscarproductosXNombre(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProXNombre[] wsBuscarproductosXNombre(string NOMBRE, System.Nullable<int> NUMERO_PAGINA, System.Nullable<int> TAMANO_PAGINA) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreRequest();
            inValue.NOMBRE = NOMBRE;
            inValue.NUMERO_PAGINA = NUMERO_PAGINA;
            inValue.TAMANO_PAGINA = TAMANO_PAGINA;
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsBuscarproductosXNombre(inValue);
            return retVal.ConsultaProXNombre;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreResponse> PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsBuscarproductosXNombreAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreRequest request) {
            return base.Channel.wsBuscarproductosXNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreResponse> wsBuscarproductosXNombreAsync(string NOMBRE, System.Nullable<int> NUMERO_PAGINA, System.Nullable<int> TAMANO_PAGINA) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductosXNombreRequest();
            inValue.NOMBRE = NOMBRE;
            inValue.NUMERO_PAGINA = NUMERO_PAGINA;
            inValue.TAMANO_PAGINA = TAMANO_PAGINA;
            return ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsBuscarproductosXNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasResponse PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsRankingCategorias(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasRequest request) {
            return base.Channel.wsRankingCategorias(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.RankingCategoria[] wsRankingCategorias(string FECHAINI, string FECHAFIN) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasRequest();
            inValue.FECHAINI = FECHAINI;
            inValue.FECHAFIN = FECHAFIN;
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsRankingCategorias(inValue);
            return retVal.RankingCategoria;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasResponse> PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsRankingCategoriasAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasRequest request) {
            return base.Channel.wsRankingCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasResponse> wsRankingCategoriasAsync(string FECHAINI, string FECHAFIN) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsRankingCategoriasRequest();
            inValue.FECHAINI = FECHAINI;
            inValue.FECHAFIN = FECHAFIN;
            return ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsRankingCategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDResponse PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsBuscarproductoXID(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDRequest request) {
            return base.Channel.wsBuscarproductoXID(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProductoXID[] wsBuscarproductoXID(System.Nullable<int> PRODUCTO_ID) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDRequest();
            inValue.PRODUCTO_ID = PRODUCTO_ID;
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsBuscarproductoXID(inValue);
            return retVal.ConsultaProductoXID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDResponse> PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsBuscarproductoXIDAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDRequest request) {
            return base.Channel.wsBuscarproductoXIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDResponse> wsBuscarproductoXIDAsync(System.Nullable<int> PRODUCTO_ID) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarproductoXIDRequest();
            inValue.PRODUCTO_ID = PRODUCTO_ID;
            return ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsBuscarproductoXIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionResponse PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsBuscarProductosXDescripcion(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionRequest request) {
            return base.Channel.wsBuscarProductosXDescripcion(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.ConsultaProXDes[] wsBuscarProductosXDescripcion(string DESCRIPCION, System.Nullable<int> NUMERO_PAGINA, System.Nullable<int> TAMANO_PAGINA) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionRequest();
            inValue.DESCRIPCION = DESCRIPCION;
            inValue.NUMERO_PAGINA = NUMERO_PAGINA;
            inValue.TAMANO_PAGINA = TAMANO_PAGINA;
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsBuscarProductosXDescripcion(inValue);
            return retVal.ConsultaProXDes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionResponse> PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType.wsBuscarProductosXDescripcionAsync(PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionRequest request) {
            return base.Channel.wsBuscarProductosXDescripcionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionResponse> wsBuscarProductosXDescripcionAsync(string DESCRIPCION, System.Nullable<int> NUMERO_PAGINA, System.Nullable<int> TAMANO_PAGINA) {
            PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.wsBuscarProductosXDescripcionRequest();
            inValue.DESCRIPCION = DESCRIPCION;
            inValue.NUMERO_PAGINA = NUMERO_PAGINA;
            inValue.TAMANO_PAGINA = TAMANO_PAGINA;
            return ((PICA_B2C.ServiceAgent.MainModule.wsConsultasProductosReference.consultasEspecialesProductosPortType)(this)).wsBuscarProductosXDescripcionAsync(inValue);
        }
    }
}
