//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string current_paramsField;
        
        private string current_request_nameField;
        
        private string nested_exceptionField;
        
        private DataServiceFaultSource_data_service source_data_serviceField;
        
        private string ds_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string current_params {
            get {
                return this.current_paramsField;
            }
            set {
                this.current_paramsField = value;
                this.RaisePropertyChanged("current_params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string current_request_name {
            get {
                return this.current_request_nameField;
            }
            set {
                this.current_request_nameField = value;
                this.RaisePropertyChanged("current_request_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nested_exception {
            get {
                return this.nested_exceptionField;
            }
            set {
                this.nested_exceptionField = value;
                this.RaisePropertyChanged("nested_exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DataServiceFaultSource_data_service source_data_service {
            get {
                return this.source_data_serviceField;
            }
            set {
                this.source_data_serviceField = value;
                this.RaisePropertyChanged("source_data_service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ds_code {
            get {
                return this.ds_codeField;
            }
            set {
                this.ds_codeField = value;
                this.RaisePropertyChanged("ds_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFaultSource_data_service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationField;
        
        private string default_namespaceField;
        
        private string descriptionField;
        
        private string data_service_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string default_namespace {
            get {
                return this.default_namespaceField;
            }
            set {
                this.default_namespaceField = value;
                this.RaisePropertyChanged("default_namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string data_service_name {
            get {
                return this.data_service_nameField;
            }
            set {
                this.data_service_nameField = value;
                this.RaisePropertyChanged("data_service_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Campanas")]
    public partial class CampanaInsPC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODRESPUESTAField;
        
        private string mSNRESPUESTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string CODRESPUESTA {
            get {
                return this.cODRESPUESTAField;
            }
            set {
                this.cODRESPUESTAField = value;
                this.RaisePropertyChanged("CODRESPUESTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MSNRESPUESTA {
            get {
                return this.mSNRESPUESTAField;
            }
            set {
                this.mSNRESPUESTAField = value;
                this.RaisePropertyChanged("MSNRESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pica.com/dss/Campanas", ConfigurationName="wsAdministrarCampanasReference.administrarCampanasPortType")]
    public interface administrarCampanasPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (CampanasInsPC) of message wsInsertaProductoCampanaResponse does not match the default value (wsInsertaProductoCampana)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsInsertaProductoCampana", ReplyAction="urn:wsInsertaProductoCampanaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.DataServiceFault), Action="urn:wsInsertaProductoCampanaDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaResponse wsInsertaProductoCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsInsertaProductoCampana", ReplyAction="urn:wsInsertaProductoCampanaResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaResponse> wsInsertaProductoCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CampanasInsert) of message wsInsertarCampanaResponse does not match the default value (wsInsertarCampana)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsInsertarCampana", ReplyAction="urn:wsInsertarCampanaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.DataServiceFault), Action="urn:wsInsertarCampanaDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaResponse wsInsertarCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsInsertarCampana", ReplyAction="urn:wsInsertarCampanaResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaResponse> wsInsertarCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CampanasConXPro) of message wsConsultarProductosXCampanaResponse does not match the default value (wsConsultarProductosXCampana)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsConsultarProductosXCampana", ReplyAction="urn:wsConsultarProductosXCampanaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.DataServiceFault), Action="urn:wsConsultarProductosXCampanaDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaResponse wsConsultarProductosXCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsConsultarProductosXCampana", ReplyAction="urn:wsConsultarProductosXCampanaResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaResponse> wsConsultarProductosXCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CampanasCons) of message wsConsultaCampanaResponse does not match the default value (wsConsultaCampana)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsConsultaCampana", ReplyAction="urn:wsConsultaCampanaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.DataServiceFault), Action="urn:wsConsultaCampanaDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaResponse wsConsultaCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsConsultaCampana", ReplyAction="urn:wsConsultaCampanaResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaResponse> wsConsultaCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CampanasAct) of message wsActualizarCampanaResponse does not match the default value (wsActualizarCampana)
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsActualizarCampana", ReplyAction="urn:wsActualizarCampanaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.DataServiceFault), Action="urn:wsActualizarCampanaDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaResponse wsActualizarCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wsActualizarCampana", ReplyAction="urn:wsActualizarCampanaResponse")]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaResponse> wsActualizarCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsInsertaProductoCampana", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsInsertaProductoCampanaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDPRODUCTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDCAMPANA;
        
        public wsInsertaProductoCampanaRequest() {
        }
        
        public wsInsertaProductoCampanaRequest(System.Nullable<int> IDPRODUCTO, System.Nullable<int> IDCAMPANA) {
            this.IDPRODUCTO = IDPRODUCTO;
            this.IDCAMPANA = IDCAMPANA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CampanasInsPC", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsInsertaProductoCampanaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CampanaInsPC")]
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaInsPC[] CampanaInsPC;
        
        public wsInsertaProductoCampanaResponse() {
        }
        
        public wsInsertaProductoCampanaResponse(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaInsPC[] CampanaInsPC) {
            this.CampanaInsPC = CampanaInsPC;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Campanas")]
    public partial class CampanaInsert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDCAMPANAField;
        
        private string cODRESPUESTAField;
        
        private string mSNRESPUESTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string IDCAMPANA {
            get {
                return this.iDCAMPANAField;
            }
            set {
                this.iDCAMPANAField = value;
                this.RaisePropertyChanged("IDCAMPANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string CODRESPUESTA {
            get {
                return this.cODRESPUESTAField;
            }
            set {
                this.cODRESPUESTAField = value;
                this.RaisePropertyChanged("CODRESPUESTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string MSNRESPUESTA {
            get {
                return this.mSNRESPUESTAField;
            }
            set {
                this.mSNRESPUESTAField = value;
                this.RaisePropertyChanged("MSNRESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsInsertarCampana", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsInsertarCampanaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NOMBRE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DESCRIPCION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHAINI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHAVENCIMIENTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO;
        
        public wsInsertarCampanaRequest() {
        }
        
        public wsInsertarCampanaRequest(string NOMBRE, string DESCRIPCION, string FECHAINI, string FECHAVENCIMIENTO, string ESTADO) {
            this.NOMBRE = NOMBRE;
            this.DESCRIPCION = DESCRIPCION;
            this.FECHAINI = FECHAINI;
            this.FECHAVENCIMIENTO = FECHAVENCIMIENTO;
            this.ESTADO = ESTADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CampanasInsert", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsInsertarCampanaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CampanaInsert")]
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaInsert[] CampanaInsert;
        
        public wsInsertarCampanaResponse() {
        }
        
        public wsInsertarCampanaResponse(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaInsert[] CampanaInsert) {
            this.CampanaInsert = CampanaInsert;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Campanas")]
    public partial class CampanaConXPro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string pRODUCTO_IDField;
        
        private string nOMBREField;
        
        private string dESCRIPCIONField;
        
        private string cATEGORIAField;
        
        private string pRECIO_LISTAField;
        
        private string fABRICANTEField;
        
        private string iMAGENField;
        
        private string iMAGEN_URLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string PRODUCTO_ID {
            get {
                return this.pRODUCTO_IDField;
            }
            set {
                this.pRODUCTO_IDField = value;
                this.RaisePropertyChanged("PRODUCTO_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
                this.RaisePropertyChanged("CATEGORIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string PRECIO_LISTA {
            get {
                return this.pRECIO_LISTAField;
            }
            set {
                this.pRECIO_LISTAField = value;
                this.RaisePropertyChanged("PRECIO_LISTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string FABRICANTE {
            get {
                return this.fABRICANTEField;
            }
            set {
                this.fABRICANTEField = value;
                this.RaisePropertyChanged("FABRICANTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string IMAGEN {
            get {
                return this.iMAGENField;
            }
            set {
                this.iMAGENField = value;
                this.RaisePropertyChanged("IMAGEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string IMAGEN_URL {
            get {
                return this.iMAGEN_URLField;
            }
            set {
                this.iMAGEN_URLField = value;
                this.RaisePropertyChanged("IMAGEN_URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsConsultarProductosXCampana", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsConsultarProductosXCampanaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDCAMPANA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO;
        
        public wsConsultarProductosXCampanaRequest() {
        }
        
        public wsConsultarProductosXCampanaRequest(System.Nullable<int> IDCAMPANA, string ESTADO) {
            this.IDCAMPANA = IDCAMPANA;
            this.ESTADO = ESTADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CampanasConXPro", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsConsultarProductosXCampanaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CampanaConXPro")]
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaConXPro[] CampanaConXPro;
        
        public wsConsultarProductosXCampanaResponse() {
        }
        
        public wsConsultarProductosXCampanaResponse(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaConXPro[] CampanaConXPro) {
            this.CampanaConXPro = CampanaConXPro;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Campanas")]
    public partial class CampanaCons : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDCAMPANAField;
        
        private string nOMBREField;
        
        private string dESCRIPCIONField;
        
        private System.Nullable<System.DateTime> fECHAINIField;
        
        private System.Nullable<System.DateTime> fECHAVENCIMIENTOField;
        
        private string eSTADOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string IDCAMPANA {
            get {
                return this.iDCAMPANAField;
            }
            set {
                this.iDCAMPANAField = value;
                this.RaisePropertyChanged("IDCAMPANA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string NOMBRE {
            get {
                return this.nOMBREField;
            }
            set {
                this.nOMBREField = value;
                this.RaisePropertyChanged("NOMBRE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> FECHAINI {
            get {
                return this.fECHAINIField;
            }
            set {
                this.fECHAINIField = value;
                this.RaisePropertyChanged("FECHAINI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> FECHAVENCIMIENTO {
            get {
                return this.fECHAVENCIMIENTOField;
            }
            set {
                this.fECHAVENCIMIENTOField = value;
                this.RaisePropertyChanged("FECHAVENCIMIENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsConsultaCampana", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsConsultaCampanaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO;
        
        public wsConsultaCampanaRequest() {
        }
        
        public wsConsultaCampanaRequest(string ESTADO) {
            this.ESTADO = ESTADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CampanasCons", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsConsultaCampanaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CampanaCons")]
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaCons[] CampanaCons;
        
        public wsConsultaCampanaResponse() {
        }
        
        public wsConsultaCampanaResponse(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaCons[] CampanaCons) {
            this.CampanaCons = CampanaCons;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pica.com/dss/Campanas")]
    public partial class CampanaAct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODRESPUESTAField;
        
        private string mSNRESPUESTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string CODRESPUESTA {
            get {
                return this.cODRESPUESTAField;
            }
            set {
                this.cODRESPUESTAField = value;
                this.RaisePropertyChanged("CODRESPUESTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MSNRESPUESTA {
            get {
                return this.mSNRESPUESTAField;
            }
            set {
                this.mSNRESPUESTAField = value;
                this.RaisePropertyChanged("MSNRESPUESTA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsActualizarCampana", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsActualizarCampanaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IDCAMPANA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NOMBRE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DESCRIPCION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHAVENCIMIENTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO;
        
        public wsActualizarCampanaRequest() {
        }
        
        public wsActualizarCampanaRequest(System.Nullable<int> IDCAMPANA, string NOMBRE, string DESCRIPCION, string FECHAVENCIMIENTO, string ESTADO) {
            this.IDCAMPANA = IDCAMPANA;
            this.NOMBRE = NOMBRE;
            this.DESCRIPCION = DESCRIPCION;
            this.FECHAVENCIMIENTO = FECHAVENCIMIENTO;
            this.ESTADO = ESTADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CampanasAct", WrapperNamespace="http://pica.com/dss/Campanas", IsWrapped=true)]
    public partial class wsActualizarCampanaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pica.com/dss/Campanas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CampanaAct")]
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaAct[] CampanaAct;
        
        public wsActualizarCampanaResponse() {
        }
        
        public wsActualizarCampanaResponse(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaAct[] CampanaAct) {
            this.CampanaAct = CampanaAct;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface administrarCampanasPortTypeChannel : PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class administrarCampanasPortTypeClient : System.ServiceModel.ClientBase<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType>, PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType {
        
        public administrarCampanasPortTypeClient() {
        }
        
        public administrarCampanasPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public administrarCampanasPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public administrarCampanasPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public administrarCampanasPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaResponse PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsInsertaProductoCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaRequest request) {
            return base.Channel.wsInsertaProductoCampana(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaInsPC[] wsInsertaProductoCampana(System.Nullable<int> IDPRODUCTO, System.Nullable<int> IDCAMPANA) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaRequest();
            inValue.IDPRODUCTO = IDPRODUCTO;
            inValue.IDCAMPANA = IDCAMPANA;
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsInsertaProductoCampana(inValue);
            return retVal.CampanaInsPC;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaResponse> PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsInsertaProductoCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaRequest request) {
            return base.Channel.wsInsertaProductoCampanaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaResponse> wsInsertaProductoCampanaAsync(System.Nullable<int> IDPRODUCTO, System.Nullable<int> IDCAMPANA) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertaProductoCampanaRequest();
            inValue.IDPRODUCTO = IDPRODUCTO;
            inValue.IDCAMPANA = IDCAMPANA;
            return ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsInsertaProductoCampanaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaResponse PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsInsertarCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaRequest request) {
            return base.Channel.wsInsertarCampana(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaInsert[] wsInsertarCampana(string NOMBRE, string DESCRIPCION, string FECHAINI, string FECHAVENCIMIENTO, string ESTADO) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaRequest();
            inValue.NOMBRE = NOMBRE;
            inValue.DESCRIPCION = DESCRIPCION;
            inValue.FECHAINI = FECHAINI;
            inValue.FECHAVENCIMIENTO = FECHAVENCIMIENTO;
            inValue.ESTADO = ESTADO;
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsInsertarCampana(inValue);
            return retVal.CampanaInsert;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaResponse> PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsInsertarCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaRequest request) {
            return base.Channel.wsInsertarCampanaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaResponse> wsInsertarCampanaAsync(string NOMBRE, string DESCRIPCION, string FECHAINI, string FECHAVENCIMIENTO, string ESTADO) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsInsertarCampanaRequest();
            inValue.NOMBRE = NOMBRE;
            inValue.DESCRIPCION = DESCRIPCION;
            inValue.FECHAINI = FECHAINI;
            inValue.FECHAVENCIMIENTO = FECHAVENCIMIENTO;
            inValue.ESTADO = ESTADO;
            return ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsInsertarCampanaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaResponse PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsConsultarProductosXCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaRequest request) {
            return base.Channel.wsConsultarProductosXCampana(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaConXPro[] wsConsultarProductosXCampana(System.Nullable<int> IDCAMPANA, string ESTADO) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaRequest();
            inValue.IDCAMPANA = IDCAMPANA;
            inValue.ESTADO = ESTADO;
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsConsultarProductosXCampana(inValue);
            return retVal.CampanaConXPro;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaResponse> PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsConsultarProductosXCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaRequest request) {
            return base.Channel.wsConsultarProductosXCampanaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaResponse> wsConsultarProductosXCampanaAsync(System.Nullable<int> IDCAMPANA, string ESTADO) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultarProductosXCampanaRequest();
            inValue.IDCAMPANA = IDCAMPANA;
            inValue.ESTADO = ESTADO;
            return ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsConsultarProductosXCampanaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaResponse PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsConsultaCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaRequest request) {
            return base.Channel.wsConsultaCampana(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaCons[] wsConsultaCampana(string ESTADO) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaRequest();
            inValue.ESTADO = ESTADO;
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsConsultaCampana(inValue);
            return retVal.CampanaCons;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaResponse> PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsConsultaCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaRequest request) {
            return base.Channel.wsConsultaCampanaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaResponse> wsConsultaCampanaAsync(string ESTADO) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsConsultaCampanaRequest();
            inValue.ESTADO = ESTADO;
            return ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsConsultaCampanaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaResponse PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsActualizarCampana(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaRequest request) {
            return base.Channel.wsActualizarCampana(request);
        }
        
        public PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.CampanaAct[] wsActualizarCampana(System.Nullable<int> IDCAMPANA, string NOMBRE, string DESCRIPCION, string FECHAVENCIMIENTO, string ESTADO) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaRequest();
            inValue.IDCAMPANA = IDCAMPANA;
            inValue.NOMBRE = NOMBRE;
            inValue.DESCRIPCION = DESCRIPCION;
            inValue.FECHAVENCIMIENTO = FECHAVENCIMIENTO;
            inValue.ESTADO = ESTADO;
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaResponse retVal = ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsActualizarCampana(inValue);
            return retVal.CampanaAct;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaResponse> PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType.wsActualizarCampanaAsync(PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaRequest request) {
            return base.Channel.wsActualizarCampanaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaResponse> wsActualizarCampanaAsync(System.Nullable<int> IDCAMPANA, string NOMBRE, string DESCRIPCION, string FECHAVENCIMIENTO, string ESTADO) {
            PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaRequest inValue = new PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.wsActualizarCampanaRequest();
            inValue.IDCAMPANA = IDCAMPANA;
            inValue.NOMBRE = NOMBRE;
            inValue.DESCRIPCION = DESCRIPCION;
            inValue.FECHAVENCIMIENTO = FECHAVENCIMIENTO;
            inValue.ESTADO = ESTADO;
            return ((PICA_B2C.ServiceAgent.MainModule.wsAdministrarCampanasReference.administrarCampanasPortType)(this)).wsActualizarCampanaAsync(inValue);
        }
    }
}
